// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'WEKA_API_KEY_YAKO_HAPA',
    appId: 'WEKA_APP_ID_YAKO_HAPA',
    messagingSenderId: 'WEKA_SENDER_ID_YAKO_HAPA',
    projectId: 'WEKA_PROJECT_ID_YAKO_HAPA',
    authDomain: 'WEKA_PROJECT_ID_YAKO_HAPA.firebaseapp.com',
    storageBucket: 'WEKA_PROJECT_ID_YAKO_HAPA.appspot.com',
    measurementId: 'WEKA_MEASUREMENT_ID_YAKO_HAPA',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'WEKA_API_KEY_YAKO_HAPA',
    appId: 'WEKA_APP_ID_YAKO_HAPA',
    messagingSenderId: 'WEKA_SENDER_ID_YAKO_HAPA',
    projectId: 'WEKA_PROJECT_ID_YAKO_HAPA',
    storageBucket: 'WEKA_PROJECT_ID_YAKO_HAPA.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'WEKA_API_KEY_YAKO_HAPA',
    appId: 'WEKA_APP_ID_YAKO_HAPA',
    messagingSenderId: 'WEKA_SENDER_ID_YAKO_HAPA',
    projectId: 'WEKA_PROJECT_ID_YAKO_HAPA',
    storageBucket: 'WEKA_PROJECT_ID_YAKO_HAPA.appspot.com',
    iosClientId: 'WEKA_IOS_CLIENT_ID_YAKO_HAPA',
    iosBundleId: 'com.example.wasindiFamilyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'WEKA_API_KEY_YAKO_HAPA',
    appId: 'WEKA_APP_ID_YAKO_HAPA',
    messagingSenderId: 'WEKA_SENDER_ID_YAKO_HAPA',
    projectId: 'WEKA_PROJECT_ID_YAKO_HAPA',
    storageBucket: 'WEKA_PROJECT_ID_YAKO_HAPA.appspot.com',
    iosClientId: 'WEKA_IOS_CLIENT_ID_YAKO_HAPA',
    iosBundleId: 'com.example.wasindiFamilyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'WEKA_API_KEY_YAKO_HAPA',
    appId: 'WEKA_APP_ID_YAKO_HAPA',
    messagingSenderId: 'WEKA_SENDER_ID_YAKO_HAPA',
    projectId: 'WEKA_PROJECT_ID_YAKO_HAPA',
    authDomain: 'WEKA_PROJECT_ID_YAKO_HAPA.firebaseapp.com',
    storageBucket: 'WEKA_PROJECT_ID_YAKO_HAPA.appspot.com',
    measurementId: 'WEKA_MEASUREMENT_ID_YAKO_HAPA',
  );
}
